[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astir"
version = "0.2.0"
description = ""
readme = "README.rst"
requires-python = ">=3.9"
license = { text = "GPLv2" }

authors = [
  { name = "Jinyu Hou" },
  { name = "Sunyun Lee" },
  { name = "Michael Geuenich" },
  { name = "Kieran Campbell", email = "kierancampbell@lunenfeld.ca" }
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Bio-Informatics"
]

dependencies = [
  "torch",
  "pandas",
  "numpy<2.0.0",
  "nbformat",
  "pyyaml",
  "scikit-learn",
  "argparse",
  "matplotlib",
  "loompy",
  "tqdm",
  "anndata",
  "rootpath",
  "nbconvert",
  "nbformat",
  "seaborn",
  "jupyter_client",
  "ipykernel",
  "ipython",
  "h5py",
  "FlowCytometryTools",
  "fastcluster",
  "sphinx",
  "sphinx_autodoc_typehints",
  "sphinx_rtd_theme",
  "autodocsumm",
  "nbsphinx",
  "nbsphinx_link",
  "tables",
  "typeguard",
  "mypy",
  "types-PyYAML"
]

[project.urls]
Documentation = "https://astir.readthedocs.io/en/latest/"
Source = "https://github.com/camlab-bioml/astir"

[project.scripts]
astir = "astir.cli:main"

[tool.setuptools.packages.find]
include = ["astir*"]
